[phases.setup]
nixPkgs = ["nodejs"]  # Указываем, что используем Node.js

[phases.build]
cmds = ["npm install"]  # Команда для сборки

[phases.install]
cmds = []  # Отключаем дополнительные шаги установки

[start]
cmd = "npm start"  # Команда для запуска приложения
